### ISSUE TITLE
Quicklisp Source Repo

### ISSUE THREAD

**Issue by ghollisjr** [herth/ltk#18]
Hi Peter,

I noticed recently that you were active on this repository and wanted to let you know what's been happening:

Due to the inactivity of this repo and multiple users making the suggestion to change Quicklisp's source repo to a more actively maintained repo, [Issue 2156](https://github.com/quicklisp/quicklisp-projects/issues/2156) was put forward to switch the LTK source repo to my own.  I tried reaching out to you via the email from [your project page](http://www.peter-herth.de/ltk/) and after not hearing back for a few weeks I reached out to other users about what to do.

Do you anticipate active development on this repository or would you also support moving the source repo to a more actively maintained one?  Or would you support something like other users having commit access to this repo if neither of the above sounds reasonable?

**Comment by herth** [comment]
Hi Gary,

thanks for your message. Yes, I haven't been very active on the maintenance of LTk, because for many years, there was nothing to maintain :). It seems to be very stable and robust and I got only very occasionally any feedback/patches. Seems moving to Github has increased that, which I quite welcome. I had received your mail, but had no opportunity to answer it immediately until you had concluded, that I wouldn't answer anyway. Generally, I am reachable via my email address. 
I am very happy, if there is more activity around LTk and would welcome contributions. I can commit to sorting through the pull request which have been accumulated so far and would be interested in future ones. However that depends a bit on the relative effort required. One thing I value very much about LTk is, that it is very stable. So reviewing a patch can take a surprising amount of time - depending how well it is prepared. As long as it doesn't take too much time efforts, I am quite happy about any patch. 

Peter

**Comment by ghollisjr** [comment]
Hi Peter,

Good to hear from you.  In this case I will remove the request to switch LTK source repos in quicklisp and just make some PRs for the issues I had fixed in my fork so you can review them when you get the time.
