### ISSUE TITLE
Symbol conflict with sb-thread:raise in latest SBCL

### ISSUE THREAD

**Issue by quicklisp** [herth/ltk#9]
I can't build due to this: `Unhandled NAME-CONFLICT in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A38083}>: USE-PACKAGE #<PACKAGE "SB-THREAD"> causes name-conflicts in #<PACKAGE "LTK-REMOTE"> between the following symbols: SB-THREAD:RAISE, LTK:RAISE`

**Comment by ghollisjr** [comment]
Is this bug still active?  There's been talk of requesting for this repo to be added to sharplispers due to lack of activity

**Comment by tfb** [comment]
SB-THREAD no longer exports "RAISE", so this is no longer an issue.

I also changed ltk-remote to directly use the symbols it needs from sbcl packages, rather than USEing them. It’s reasonable to expect them to be more dynamic than, say, CMUCL. This should prevent issues like this from coming up again.
